version: '3'
services:
  dbservice:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      # -MYSQL-USERNAME=username
      #
    volumes:
      - ./data:/var/lib/mysql

    ports:
      - 3306:3306
      
    networks:
      - bootapp
    
  appservice:
    build: ./boot
    depends_on:
      - dbservice
    environment:
      - spring.datasource.url=jdbc:mysql://dbservice:3306/blog_app?createdatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=root
    ports:
      - 8085:9292

    networks:
      - bootapp

networks:
  bootapp: